# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_slug_field_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteam',
            name='FERPA_protected',
            field=models.BooleanField(default=False),
        ),
    ]
